package Wilkenfeld_Montessori;

import java.awt.Color;
import java.util.HashMap;

public class WelcomeFrame extends javax.swing.JFrame {
    public WelcomeFrame() {
        initComponents();

        // after initComponents();
        getContentPane().setBackground(new Color(240,240,232)); // or Color.RED

        UserinfoLabel.setVisible(false);
        LogoutButton.setVisible(false);
        ScoresPanel.setVisible(false);
        ProfilePanel.setVisible(false);
        RegisterPanel.setVisible(false);

        String u = "gswilken";
        String p = "seth";
        userHash.put(u, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        ScoresButton = new javax.swing.JButton();
        LoginFormPanel = new javax.swing.JLayeredPane();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        UserinfoLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ContentPane = new javax.swing.JLayeredPane();
        WelcomePanel = new javax.swing.JPanel();
        WelcomeTitle = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ScoresPanel = new javax.swing.JPanel();
        ScoresTitle = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        ProfileTitle = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        RegisterTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/WelcomeButtonBase.png"))); // NOI18N
        WelcomeButton.setBorder(null);
        WelcomeButton.setBorderPainted(false);
        WelcomeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/WelcomeButtonPressed.png"))); // NOI18N
        WelcomeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/WelcomeButtonSelected.png"))); // NOI18N
        WelcomeButton.setSelected(true);
        WelcomeButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/WelcomeButtonSelected.png"))); // NOI18N
        WelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeButtonActionPerformed(evt);
            }
        });

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/PlayButtonBase.png"))); // NOI18N
        PlayButton.setBorder(null);
        PlayButton.setBorderPainted(false);
        PlayButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/PlayButtonPressed.png"))); // NOI18N
        PlayButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/PlayButtonSelected.png"))); // NOI18N
        PlayButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/PlayButtonSelected.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        ScoresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ScoreButtonBase.png"))); // NOI18N
        ScoresButton.setBorder(null);
        ScoresButton.setBorderPainted(false);
        ScoresButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ScoreButtonPressed.png"))); // NOI18N
        ScoresButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ScoreButtonSelected.png"))); // NOI18N
        ScoresButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ScoreButtonSelected.png"))); // NOI18N
        ScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoresButtonActionPerformed(evt);
            }
        });

        UsernameField.setText("username...");
        UsernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameFieldMouseClicked(evt);
            }
        });
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        UsernameField.setBounds(0, 0, 120, 41);
        LoginFormPanel.add(UsernameField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PasswordField.setText("password...");
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseClicked(evt);
            }
        });
        PasswordField.setBounds(130, 0, 120, 41);
        LoginFormPanel.add(PasswordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        UserinfoLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserinfoLabel.setText("jLabel1");
        UserinfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UserinfoLabel.setBounds(0, 0, 250, 40);
        LoginFormPanel.add(UserinfoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/LoginButtonBase.png"))); // NOI18N
        LoginButton.setBorder(null);
        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/LoginButtonPressed.png"))); // NOI18N
        LoginButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/LoginButtonSelected.png"))); // NOI18N
        LoginButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/LoginButtonSelected.png"))); // NOI18N
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginButton.setBounds(250, 0, 130, 41);
        LoginFormPanel.add(LoginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ProfileButtonBase.png"))); // NOI18N
        ProfileButton.setAlignmentY(0.0F);
        ProfileButton.setBorder(null);
        ProfileButton.setBorderPainted(false);
        ProfileButton.setContentAreaFilled(false);
        ProfileButton.setHideActionText(true);
        ProfileButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ProfileButtonPressed.png"))); // NOI18N
        ProfileButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ProfileButtonSelected.png"))); // NOI18N
        ProfileButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/ProfileButtonSelected.png"))); // NOI18N
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });
        ProfileButton.setBounds(250, 0, 130, 41);
        LoginFormPanel.add(ProfileButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        RegisterButton.setBackground(new java.awt.Color(240, 240, 232));
        RegisterButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.setBorder(null);
        RegisterButton.setBorderPainted(false);
        RegisterButton.setContentAreaFilled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        RegisterButton.setBounds(260, 40, 110, 30);
        LoginFormPanel.add(RegisterButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LogoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        LogoutButton.setBounds(260, 40, 110, 30);
        LoginFormPanel.add(LogoutButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContentPane.setBackground(new java.awt.Color(255, 255, 255));

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 255));
        WelcomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        WelcomeTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        WelcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle.setText("Welcome to the Montessori Grammar Game!");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/nounThumb.PNG"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/verbThumb.PNG"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/adjectiveThumb.PNG"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/adverbThumb.PNG"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/conjunctionThumb.PNG"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/articleThumb.PNG"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/interjectionThumb.PNG"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/prepositionThumb.PNG"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shapes/pronounThumb.PNG"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("You will be given a sentence, with some (or all) of the words underlined,  and some (or all) of");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("the shapes you see to the left and right of this page. Drag the appropriate shapes to the space");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("under the word you want to label. The level of difficulty you select will determine which words");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("require labels, as well as which shapes (labels) are available:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Beginner:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("• Nouns");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("• Verbs");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Intermediate:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("• Adjectives");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("• Adverbs");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("• Conjunctions");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Advanced:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("• Prepositions");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("• Pronouns");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("• Articles");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("• Interjections");

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WelcomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(WelcomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(153, 153, 153)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addGap(56, 56, 56)))
                .addGap(18, 18, 18)
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WelcomePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7)
                                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGap(32, 32, 32)
                                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WelcomePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel15))
                                        .addGroup(WelcomePanelLayout.createSequentialGroup()
                                            .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(WelcomePanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel10))
                                                .addGroup(WelcomePanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel7)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addGap(56, 56, 56)))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel16)
                                .addContainerGap(39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(29, 29, 29)
                                .addComponent(jButton4)
                                .addContainerGap())))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WelcomePanelLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addContainerGap())
                            .addGroup(WelcomePanelLayout.createSequentialGroup()
                                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                                        .addGap(211, 211, 211)
                                        .addComponent(jButton2))
                                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton1)))
                                .addGap(37, 37, 37))))))
        );

        WelcomePanel.setBounds(0, 0, 980, 480);
        ContentPane.add(WelcomePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ScoresPanel.setBackground(new java.awt.Color(255, 255, 255));
        ScoresPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ScoresTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        ScoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoresTitle.setText("Montessori Hall of Fame!");

        javax.swing.GroupLayout ScoresPanelLayout = new javax.swing.GroupLayout(ScoresPanel);
        ScoresPanel.setLayout(ScoresPanelLayout);
        ScoresPanelLayout.setHorizontalGroup(
            ScoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoresPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(ScoresTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        ScoresPanelLayout.setVerticalGroup(
            ScoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScoresTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        ScoresPanel.setBounds(0, 0, 980, 480);
        ContentPane.add(ScoresPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ProfilePanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfilePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ProfileTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        ProfileTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileTitle.setText("Edit your profile:");

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePanelLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(ProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        ProfilePanel.setBounds(0, 0, 980, 480);
        ContentPane.add(ProfilePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RegisterTitle.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        RegisterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterTitle.setText("Register new user:");

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(RegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        RegisterPanel.setBounds(0, 0, 980, 480);
        ContentPane.add(RegisterPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContentPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(WelcomeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PlayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScoresButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoginFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(WelcomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LoginFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        username = UsernameField.getText();
        String password = PasswordField.getText();

        if(userHash.containsKey(username))
            if(userHash.get(username).equals(password)) {
                UsernameField.setVisible(false);
                PasswordField.setVisible(false);
                LoginButton.setVisible(false);
                RegisterButton.setVisible(false);
                UserinfoLabel.setVisible(true);
                LogoutButton.setVisible(true);
                UserinfoLabel.setText("Welcome " + username + "!");
            }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void WelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeButtonActionPerformed
        SetVisiblePanel("Welcome");
        SetSelectedButton("Welcome");
    }//GEN-LAST:event_WelcomeButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        PlayFrame1 myPlayFrame = new PlayFrame1();
        if(username != null)
            myPlayFrame.setUsername(username);
        myPlayFrame.setVisible(true);
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void ScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoresButtonActionPerformed
        SetVisiblePanel("Scores");
        SetSelectedButton("Scores");
    }//GEN-LAST:event_ScoresButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        SetVisiblePanel("Register");
        SetSelectedButton("Register");
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void UsernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMouseClicked
        UsernameField.setText("");
    }//GEN-LAST:event_UsernameFieldMouseClicked

    private void PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseClicked
        PasswordField.setText("");
    }//GEN-LAST:event_PasswordFieldMouseClicked

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        username = null;

        UsernameField.setVisible(true);
        PasswordField.setVisible(true);
        LoginButton.setVisible(true);
        RegisterButton.setVisible(true);
        LogoutButton.setVisible(false);
        UserinfoLabel.setVisible(false);

        UserinfoLabel.setText("");
        UsernameField.setText("");
        PasswordField.setText("");

        WelcomeButtonActionPerformed(evt);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        SetVisiblePanel("Profile");
        SetSelectedButton("Profile");
    }//GEN-LAST:event_ProfileButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    private void SetVisiblePanel(String pnl) {
        if(WelcomePanel.isVisible()) {
            WelcomePanel.setVisible(false);
        } else if(ScoresPanel.isVisible()) {
            ScoresPanel.setVisible(false);
        } else if(RegisterPanel.isVisible()) {
            RegisterPanel.setVisible(false);
        } else if(ProfilePanel.isVisible()) {
            ProfilePanel.setVisible(false);
        }

        if(pnl.equals("Welcome")) {
            WelcomePanel.setVisible(true);
        } else if(pnl.equals("Scores")) {
            ScoresPanel.setVisible(true);
        } else if(pnl.equals("Register")) {
            RegisterPanel.setVisible(true);
        } else if(pnl.equals("Profile")) {
            ProfilePanel.setVisible(true);
        }
    }

    private void SetSelectedButton(String bttn) {
        if(WelcomeButton.isSelected()) {
            WelcomeButton.setSelected(false);
        } else if(PlayButton.isSelected()) {
            PlayButton.setSelected(false);
        } else if(ScoresButton.isSelected()) {
            ScoresButton.setSelected(false);
        } else if(LoginButton.isSelected()) {
            LoginButton.setSelected(false);
        } else if(RegisterButton.isSelected()) {
            RegisterButton.setSelected(false);
        } /*else if(ProfileButton.isSelected()) {
            ProfileButton.setSelected(false);
        }*/

        if(bttn.equals("Welcome")) {
            WelcomeButton.setSelected(true);
        } else if(bttn.equals("Play")) {
            PlayButton.setSelected(true);
        } else if(bttn.equals("Scores")) {
            ScoresButton.setSelected(true);
        } else if(bttn.equals("Login")) {
            LoginButton.setSelected(true);
        } else if(bttn.equals("Register")) {
            RegisterButton.setSelected(true);
        } /*else if(bttn.equals("Profile")) {
            ProfileButton.setSelected(true);
        }*/
    }

    HashMap userHash = new HashMap();
    private String username = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ContentPane;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLayeredPane LoginFormPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JLabel ProfileTitle;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JLabel RegisterTitle;
    private javax.swing.JButton ScoresButton;
    private javax.swing.JPanel ScoresPanel;
    private javax.swing.JLabel ScoresTitle;
    private javax.swing.JLabel UserinfoLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton WelcomeButton;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel WelcomeTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}